/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertsHost: typeof import('./components/AlertsHost.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChatMessages: typeof import('./components/ChatMessages.vue')['default']
    ConversationList: typeof import('./components/ConversationList.vue')['default']
    ConversationListItem: typeof import('./components/ConversationListItem.vue')['default']
    ConversationScreen: typeof import('./components/ConversationScreen.vue')['default']
    DisplayObject: typeof import('./components/DisplayObject.vue')['default']
    ForgotPassword: typeof import('./components/auth/ResetPassword.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Login: typeof import('./components/auth/Login.vue')['default']
    NewActivityForm: typeof import('./components/NewActivityForm.vue')['default']
    PlannedActivities: typeof import('./components/PlannedActivities.vue')['default']
    PreviousActivities: typeof import('./components/PreviousActivities.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuggestionBox: typeof import('./components/SuggestionBox.vue')['default']
    SuggestionCard: typeof import('./components/SuggestionCard.vue')['default']
    SuggestionForm: typeof import('./components/SuggestionForm.vue')['default']
  }
}
