/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/Accordion.vue')['default']
    AccordionGroup: typeof import('./components/AccordionGroup.vue')['default']
    AccountApproval: typeof import('./components/AccountApproval.vue')['default']
    ActivePoll: typeof import('./components/ActivePoll.vue')['default']
    AlertsHost: typeof import('./components/AlertsHost.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ApplicationBar: typeof import('./components/ApplicationBar.vue')['default']
    ChatMessages: typeof import('./components/ChatMessages.vue')['default']
    ClosedPoll: typeof import('./components/ClosedPoll.vue')['default']
    ConversationList: typeof import('./components/ConversationList.vue')['default']
    ConversationListItem: typeof import('./components/ConversationListItem.vue')['default']
    ConversationScreen: typeof import('./components/ConversationScreen.vue')['default']
    CreatePollForm: typeof import('./components/CreatePollForm.vue')['default']
    DisplayObject: typeof import('./components/DisplayObject.vue')['default']
    EChart: typeof import('./components/charts/EChart.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InitMemberListItem: typeof import('./components/InitMemberListItem.vue')['default']
    InitMemberRegistration: typeof import('./components/InitMemberRegistration.vue')['default']
    LeftNavigationDrawer: typeof import('./components/LeftNavigationDrawer.vue')['default']
    MouseTracker: typeof import('./components/MouseTracker.vue')['default']
    NewActivityForm: typeof import('./components/NewActivityForm.vue')['default']
    PlannedActivities: typeof import('./components/PlannedActivities.vue')['default']
    PreviousActivities: typeof import('./components/PreviousActivities.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignInForm: typeof import('./components/SignInForm.vue')['default']
    SuggestionCard: typeof import('./components/SuggestionCard.vue')['default']
    SuggestionForm: typeof import('./components/SuggestionForm.vue')['default']
    UnderConstruction: typeof import('./components/UnderConstruction.vue')['default']
  }
}
