/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/activities': RouteRecordInfo<'/activities', '/activities', Record<never, never>, Record<never, never>>,
    '/chat': RouteRecordInfo<'/chat', '/chat', Record<never, never>, Record<never, never>>,
    '/init-reg': RouteRecordInfo<'/init-reg', '/init-reg', Record<never, never>, Record<never, never>>,
    '/membership': RouteRecordInfo<'/membership', '/membership', Record<never, never>, Record<never, never>>,
    '/polls': RouteRecordInfo<'/polls', '/polls', Record<never, never>, Record<never, never>>,
    '/request-password-reset': RouteRecordInfo<'/request-password-reset', '/request-password-reset', Record<never, never>, Record<never, never>>,
    '/reset-password': RouteRecordInfo<'/reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
    '/settings': RouteRecordInfo<'/settings', '/settings', Record<never, never>, Record<never, never>>,
    '/sign-in': RouteRecordInfo<'/sign-in', '/sign-in', Record<never, never>, Record<never, never>>,
    '/suggestion-box': RouteRecordInfo<'/suggestion-box', '/suggestion-box', Record<never, never>, Record<never, never>>,
  }
}
