version: '3.8'

services:
  rangwena-nest-api:
    build:
      context: sahihi-interior-builders-api
      dockerfile: Dockerfile
    container_name: sahihi_api
    depends_on:
      - mysql_db
    ports:
      - "5000:3000"
    environment:
      - VUE_FRONTEND=http://localhost:4000
      - DATABASE_URL=mysql://sahihi_mysql_user:sahihi_mysql_password@mysql_db:3306/sahihi_mysql_database
      - JWT_SECRET="xa5FKG7rDZLX8CKnmMktLp4ljuZqGGzQBBAF5eCW9hwKAR5Gibs4ucivymaZTdihVMaSVKQ+ToYECC3EL+Qa0w=="
      - PORT=3000
    networks:
      - dev_rangwena_network

  rangwena-vuetify:
    build:
      context: sahihi-interior-builders-vue
      dockerfile: Dockerfile
    container_name: sahihi_vue
    depends_on:
      - sahihi-api
    ports:
      - "4000:80"
    networks:
      - dev_rangwena_network

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq

  redis:
    build:
      context: infrastructure_services/redis
      dockerfile: Dockerfile
    container_name: dev_redis_rangwena
    environment:
      REDIS_PASSWORD: redis_password
    ports:
      - "6379:6379"
    networks:
      - dev_rangwena_network


  postgres_db:
    build:
      context: infrastructure_services/postgres
      dockerfile: Dockerfile
    container_name: dev_postgres_rangwena
    environment:
      POSTGRES_DB: db_rangwena
      POSTGRES_USER: user_rangwena
      POSTGRES_PASSWORD: password_rangwena
    ports:
      - "5433:5432"
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    networks:
      - dev_rangwena_network

networks:
  dev_rangwena_network: {}

# volumes:
#   postgres-data:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: ./infrastructure_services/db/postgres/data