services:
  rangwena-nest-api:
    build:
      context: nest-rangwena
      dockerfile: Dockerfile
    container_name: nest_rangwena_api
    depends_on:
      - postgres_db
    ports:
      - "5001:3000"
    environment:
      - VUE_FRONTEND=http://localhost:4000
      - DATABASE_URL=postgresql://user_rangwena:password_rangwena@postgres_db:5432/db_rangwena
      - DIRECT_URL=postgresql://user_rangwena:password_rangwena@postgres_db:5432/db_rangwena
      - JWT_SECRET="xa5FKG7rDZLX8CKnmMktLp4ljuZqGGzQBBAF5eCW9hwKAR5Gibs4ucivymaZTdihVMaSVKQ+ToYECC3EL+Qa0w=="
      - PORT=3000
      - MAIL_SERVICE="Gmail"
      - MAIL_HOST="smtp.gmail.com"
      - MAIL_PORT=465
      - MAIL_USER="erickochieng766@gmail.com"
      - MAIL_PASSWORD="jfhf vqqq ahwu biev"
      - MAIL_FROM="erickochieng766@gmail.com"
      - REDIS_HOST=dev_redis_rangwena
      - REDIS_PORT=6379
    networks:
      - dev_rangwena_network

  rangwena-vuetify:
    build:
      context: vuetify-rangwena
      dockerfile: Dockerfile
    container_name: vuetified_rangwena_web
    depends_on:
      - rangwena-nest-api
    ports:
      - "4000:80"
    networks:
      - dev_rangwena_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - dev_rangwena_network

  redis:
    build:
      context: infrastructure_services/redis
      dockerfile: Dockerfile
    container_name: dev_redis_rangwena
    environment:
      REDIS_PASSWORD: redis_password
    ports:
      - "6379:6379"
    networks:
      - dev_rangwena_network

  postgres_db:
    build:
      context: infrastructure_services/postgres
      dockerfile: Dockerfile
    container_name: dev_postgres_rangwena
    environment:
      POSTGRES_DB: db_rangwena
      POSTGRES_USER: user_rangwena
      POSTGRES_PASSWORD: password_rangwena
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev_rangwena_network

networks:
  dev_rangwena_network: {}

volumes:
  postgres_data:
  rabbitmq_data: