name: Docker Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug context
        run: |
          pwd
          ls -la
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          echo "Repository: ${{ github.repository }}"
          echo "Current location:"
          tree -L 2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}
          file: ./Dockerfile
          push: true
          build-args: |
            GIT_COMMIT_SHA=${{ github.sha }}
          tags: |
            elimuhub/api:rangwena-latest
            